backend-dir: no-server
compatibility: ^1.0.0-alpha.1
dependencies: {}
description: MORB_SLAM Map Viewer and the Current Frame Displayer
docker-base: alpine
frontend-dir: no-server
icon: null
name: null
private_include: null
slug: morb_viewer
src: null
version: 1.0.0
