backend-dir: null
compatibility: ^1.0.0-alpha.1
cpp-deps: !!set {}
dependencies: {}
description: null
docker-base: alpine
frontend-dir: null
icon: null
include: null
name: null
private_include: null
slug: morb_viewer
src: null
version: 1.0.0
