backend-dir: no-server
compatibility: ^1.0.0-alpha.1
dependencies:
  morb_dbow2: Thirdparty/DBoW2
  morb_g2o: Thirdparty/g2o
  morb_sophus: Thirdparty/Sophus
description: An Accurate Open-Source Library for Visual-Inertial and Multi-Map SLAM
docker-base: alpine
frontend-dir: no-server
icon: null
name: MORB SLAM
slug: morb_slam
version: 0.1.0
